baseurl = "https://example.org/"
title = "Organic Accessories"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

publishDir = "docs"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "red"
  description = "We are a clothing and accessories boutique, located in Coppell, Texas. Our unique goods are hand-chosen and designed for women who want to dress with a casual contemporary style. Stay in touch with us via the links below to see our seasonal sales and products, or email me to setup an appointment and see how I can help you express your style."


  copyright = "&copy;2018 Organic Accessories"
  sidebarAbout = [
    "We are a clothing and accessories boutique, located in Coppell, Texas. Our uniquely selected goods are chosen by the owner and designed for women who want to dress with a casual contemporary style. Stay in touch with us via the links below to see our seasonal sales and products, or email me to setup an appointment and see how I can help you express your style."
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "kkjett24@gmail.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  instagram     = "https://www.instagram.com/organic_accessories/?hl=en"
  facebook      = "https://www.facebook.com/organic.accessories/?ref=br_rs"
  email         = "kkjett24@gmail.com"
